#!/usr/bin/python
############################################################################################################################################################################################################################################Monitoring System###################################################################################
#Created by : Aharon Nadav#

#####Ping#####
import subprocess
google = '8.8.8.8'
internaldns = '192.168.192.222'
ping_command = "ping -c 5 -n -W 4 " + google
def ping():
        (output, error) = subprocess.Popen(ping_command,
                                           stdout=subprocess.PIPE,
                                           stderr=subprocess.PIPE,
                                           shell=True).communicate()

        print output ,error

ping()

